version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 271109
      MYSQL_DATABASE: webbanhangtest
      MYSQL_USER: duc_viet_dz
      MYSQL_PASSWORD: 271109
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db_data: